hash-format = "sha256"

[[files]]
file = "mods/axiom.pw.toml"
hash = "51904b724fd8762c97dcb28daefe5940796494ea609fafe652f4d2332abb69f1"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "e65f1856eed8725712eb26dd607cbed73de44b430bb069ba543ff706b35b2603"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "5284f6d141a990f4ea021c12b851e07102f5cb22743cf7b33be6ad2eb4c8d3f5"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "d917697e84a95f857a447d26f94d93169a5a62176c93193cdf80c8d8bc1e280a"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "be0c8881821da897824770b2a71f0f3765a233eda69b295fa5b92ffe8a25014c"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "531a8d239c952428d9a633ff99cb03461656ada28decbe2e1ef19f60f7fd5726"
metafile = true
