hash-format = "sha256"

[[files]]
file = "mods/axiom.pw.toml"
hash = "c72ebeb68ad5a54c5ffe8ea916acf1584b4171fe2d9be0523975586746ab2e59"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "5c477b0cd218ed14c178205ad498aa7f3eb1ec56444c2e760e0413e8d520c064"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "402ce406f23b8de2dd79d79ea42a7fa487e9ba6264bd59e9034da4e5cb548d7a"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "26a6c62dd5e1b6812ffdf82fa05d64513100661704a3b247e7e88f10a8143923"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "f7c5f0d1e8711e621222474017e44e2de28d6df83db928f7e93502ea16715330"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "531a8d239c952428d9a633ff99cb03461656ada28decbe2e1ef19f60f7fd5726"
metafile = true
