hash-format = "sha256"

[[files]]
file = "config/inventoryprofilesnext/integrationHints/exampleIntegrationHints.json"
hash = "ca413dea02cce69c69dccdc525fb0ec013236876eff2d142772c68db3d772d3a"

[[files]]
file = "config/inventoryprofilesnext/inventoryprofiles.json"
hash = "f2fbd741090c80f8a4bb8d27fc9731e3b679c64807722ec510b764c9f57f3256"

[[files]]
file = "config/inventoryprofilesnext/pixie.einarjegorov.com&25565/lockSlots.txt"
hash = "fde6cc146065dc5ca39a1bfb9d562e0ad95a378d29a938390cd1963186e2356e"

[[files]]
file = "config/inventoryprofilesnext/pixie.einarjegorov.com&25565/villager-trading-config-v2.json"
hash = "d8159a94fc4562651a5c47dc83e46a7fd71dd70e143fca53d7b288393a87b4ef"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "904365e7891802e522e5a35189b7039e18f56a22ab30bd99af59b97ec4b7468e"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "e19edfaebfc436b6355adc94d4517192adb78b964a98d755ecf2b2d97a318224"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
hash = "2515110b3990de9703158168c22b4ecafc739c399e421daedbfba24442224ba5"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "e661900027e02f1d44f54559e8d67a0b3b507b831be4eb05ab73a0133b22791e"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "45abf05e1cc90006aeb65e4e1bbe97da5a1984f547ea8028a077dae68af0ac11"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "408151861cc1b1a4c4e9c8a3550662a2fc36d0ea96ee07b7e96c5d2a6afacf6f"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "b17d6a857c81a6692fed9431d7b7defc1a9546e3e6a299fb287d2d58b44c819f"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "93b2f668a96e7ef60f6bd15150d6dfc3b40e2c1504f5bcd79dfead63f866edfa"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "276947b1f9933ca2220a00736aba177e4034ca9a45cad9f258abf762fdb3bb0b"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "71255e25b05b6529d6a2873e4db079b7b6541f58a78d872bc19478afcb0ffd1c"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "036576f257416774276edc60372a1265f28dd6bec765c72fef9aa9d164f2a148"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "e77f26bbef9da52a1c1fe5f32eb91fe647ae4e62bc2734d3e8f894c25f3c019e"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "831a82763a6dfcdc3ec08c4dd387f12efa09c986e0c2ff48c500c4333038288a"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "554f0305025ef26b68e26554cb5fbf97ffd7aefe5ba306619f98684436569272"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "51ff93e279e03cb3cd77a5be0df777cdcd975d35b5149180d9dc724e47168c76"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "44f00c1a0e3d4f8717e805c30c862a597e7856472e72637800fd1a38d73fbd08"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "e674752dd4dd07c33d9b94f6e19c15ef893c356c3c5ed77aeaf35cf6d2325130"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "26f917bd8375d8bef56bc2976ce6ac0f36e1a08398fbc6cad4ee637f1638f158"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "9ff1a261860fcb16a7c7f124d738abcdfc1297363412d237540685003ff04d6b"
metafile = true

[[files]]
file = "mods/smooth-scroll.pw.toml"
hash = "2c4c5f6afde7fc7a310ecb7e9afd2f28e0e62d3f41c26ea4367b925622cc9bb0"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "9d340481c374a20067d1748c1a4991626bce9d7812f0bdb96072cd7a15d35462"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "b01870e848aee7e1a2e19c6530bdd4c479b21a2f6f67134da75210844252d48f"
metafile = true

[[files]]
file = "mods/voice-chat-interaction.pw.toml"
hash = "ee63322f2464e89370cf12c55740929876bf4591ab17b1ff4204d331c5cd272f"
metafile = true

[[files]]
file = "servers.dat"
hash = "c060c18ce52b9301db5bc33b8dafe9963b39d61f2be3f1fecd53d22de85a8ad4"
