hash-format = "sha256"

[[files]]
file = "mods/sodium.pw.toml"
hash = "dd8c7eed10a3639d76595603142e1d18f6d26262747138c9442d70311006be5e"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "531a8d239c952428d9a633ff99cb03461656ada28decbe2e1ef19f60f7fd5726"
metafile = true
