hash-format = "sha256"

[[files]]
file = "mods/axiom.pw.toml"
hash = "c72ebeb68ad5a54c5ffe8ea916acf1584b4171fe2d9be0523975586746ab2e59"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "b38c98a509f04f2721e0c030cb9e6410d42d266316767ce16a6b47656e8c407e"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "005c09fba7f8ce6e9966fc73914406e2a2b5e9179dbf4dfd82e8ea57ad9c5103"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "5cda5f9088650ebcccd99a7fb48f234115dc0a43a7c72b480d598a4986d0a613"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "2189db98aed03bc4516a7bef1aa2165a4495a8371b318b0285b59e6552faefcb"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "531a8d239c952428d9a633ff99cb03461656ada28decbe2e1ef19f60f7fd5726"
metafile = true
