name = "gpack"
author = "vlasovich"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f2238b4ee92e43c3a7d56786adc3bed4161d3ed14272aa09bd0868685b109df"

[versions]
fabric = "0.18.4"
minecraft = "1.21"
