name = "gpack"
author = "vlasovich"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e2b7124a999df2c5254a6959fc2c4e65f498b452979057602267bfe52c480a4"

[versions]
fabric = "0.18.4"
minecraft = "1.20.2"
