name = "gpack"
author = "vlasovich"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e579616ee5b05ce7f90788e2ab34eddb2a4847284bef62ecdbe300f88684869d"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
